### PR TITLE
Upgrade angular to version 11

### PR DESCRIPTION
**Pull request by blacksponge**
## Purpose

Upgrade to angular 11

## Context

\-

## Changes

* Upgarde to angular 11

## How to test this PR

* Run the GUI, check that nothing is broken
* Build a release, it should compile successfully

### CODE REVIEW

**Comment by matsduf** [comment]
Does this require an update of the build environment? See [Ubuntu Node.js Build Environment].

[Ubuntu Node.js Build Environment]: https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md

**Comment by blacksponge** [comment]
> Does this require an update of the build environment?

No, it still uses node 16.

**Review by pnax — APPROVED** [review]
lgtm

**Review by matsduf — APPROVED** [review]
I approve.

**Pull request merged**
