### PR TITLE
Removes dead code

### PR DESCRIPTION
**Pull request by matsduf**

### CODE REVIEW

**Comment by mattias-p** [comment]
Looks good to me, but I'd prefer if @pamasse could review this.

**Review by pnax — APPROVED** [review]
Looks good to me. (and it seems like this code is here since the first commit so might be safe to remove from my point of view).

**Comment by matsduf** [comment]
> Looks good to me. (and it seems like this code is here since the first commit so might be safe to remove from my point of view).

I have also consulted @pamasse for this issue.

**Comment by matsduf** [comment]
> Looks good to me, but I'd prefer if @pamasse could review this.

I have already consulted @pamasse.

**Review by pamasse — APPROVED** [review]

**Pull request merged**
