### PR TITLE
use github action instead of travis

### PR DESCRIPTION
**Pull request by blacksponge**
## Purpose

Switch from travis to github action.

## Context

The e2e tests do some screenshot comparison and I can't understand why the screenshot done in CI is different from the one I do in a docker container. I suspect that the font is different but I don't know which one is used in travis.

## Changes

This switch to github action in the hope that the environment is more similar from the one that I am reproducing locally.

## How to test this PR

\-

### CODE REVIEW

**Comment by marc-vanderwal** [comment]
I see no drawbacks on using Github actionts instead of Travis.

But do we really have no means at all of getting access to the screenshots taken under Travis? It may be a more subtle issue

**Review by marc-vanderwal — DISMISSED** [review]

**Review by matsduf — CHANGES_REQUESTED** [review]
This PR should be tested in Github actions, shouldn't it? That has not been done. I want to see a successful test before approving.

**Comment by blacksponge** [comment]
> This PR should be tested in Github actions, shouldn't it? That has not been done. I want to see a successful test before approving.

Theoretically yes, I am not sure I can without merging, though.

I tested the workflow locally using https://github.com/nektos/act with success.

**Comment by matsduf** [comment]
> > This PR should be tested in Github actions, shouldn't it? That has not been done. I want to see a successful test before approving.
> 
> Theoretically yes, I am not sure I can without merging, though.

I might be that it must be in a branch in Zonemaster-GUI first, so theoretically merging it to another branch and then creating a dummy PR against that. On the other hand, if you merge it to develop and create a PR, it can easily be reverted if it does not work.

**Review by matsduf — APPROVED** [review]

**Comment by blacksponge** [comment]
I am currently testing it on my local fork.

**Comment by blacksponge** [comment]
I had a syntax issue but it is now corrected, you can see the run on my fork : https://github.com/blacksponge/zonemaster-gui/actions/runs/5119880160/jobs/9205692504

**Review by matsduf — APPROVED** [review]
Please create an empty PR after merging to verify that it works as expected.

**Comment by blacksponge** [comment]
Test pull request created https://github.com/zonemaster/zonemaster-gui/pull/425, it is working as expected.

**Pull request merged**
