### PR TITLE
Add German language support in GUI

### PR DESCRIPTION
**Pull request by Virinum**
Translated files:

- [x] `de.json`
- [ ] `gui-faq-de.md`

Which other files do I have to adjust?

Also why is `gui-faq-*` listed in `.gitignore`? With this `gui-faq-de.md` gets ignored.

### CODE REVIEW

**Comment by matsduf** [comment]
Thank you for contributing, and welcome onboard as translator!

Being a translator is a life-time commitment. -- I am kidding, but not completely. -- When Zonemaster is updated, then the translations have to be updated. That happens twice a year. -- I hope you are prepared for that.

Please base your pull requests on updated develop branch, and create the PR against the develop branch. In this case, just change the target branch.

> Which other files do I have to adjust?

Well, there are a few more. For GUI it is only those two that you have already identified, `de.json` and `gui-faq-de.md` that you have to create. The other changes in GUI we will take care of. But here is an instruction (in develop branch), [TranslationGuide]

Usually we start [Zonemaster-Engine] and [Zonemaster-CLI]. Without the translation in Zonemaster-Engine it will not work to have GUI translated.

In Zonemaster-Engine `share/de.po` must be created (translated) by you, see [Translation-translators]. This translation work is the heaviest.

In Zonemaster-CLI, also `share/de.po`must be created (translated). There is no separate instruction, but the one for Zonemaster-Engine will apply.

Also in Zonemaster-Backend `de` must be added, but we will do that.

On top, the installation instructions for Zonemaster-CLI and Zonemaster-Backend must be updated, but we will do that.

> Also why is `gui-faq-*` listed in `.gitignore`? With this `gui-faq-de.md` gets ignored.

I also wondered. It has been corrected in develop branch by #183.

[TranslationGuide]: https://github.com/zonemaster/zonemaster-gui/blob/develop/docs/TranslationGuide.md
[Zonemaster-Engine]: https://github.com/zonemaster/zonemaster-engine
[Zonemaster-CLI]: https://github.com/zonemaster/zonemaster-cli
[Translation-translators]: https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/Translation-translators.md

**Comment by matsduf** [comment]
@Virinum, are you still interested in contributing with at translation or should this be closed? Please see my https://github.com/zonemaster/zonemaster-gui/pull/190#issuecomment-803674634 above.

**Comment by Virinum** [comment]
Sorry for the late response.

I think it‘s a bit too much to translate for me. I don’t have the time right now. So I’m closing this PR.
Maybe if I find some time in the future I will look at this again.

**Comment by matsduf** [comment]
Thank you for your response. No worries about the time. -- Thank you for your interest.

**Pull request closed without merging**
