### PR TITLE
type profil

### PR DESCRIPTION
**Pull request by rsau**

### CODE REVIEW

**Comment by matsduf** [comment]
@pamasse, this should be fine, shouldn't it?

**Comment by pamasse** [comment]
> @pamasse, this should be fine, shouldn't it?

Hi mats, no this is a static typo correction, we should use the i18n module in order to translate the word in all language. 

If I check with google translate: 
fr: profil
en: profile
sv: profil
da: profil

**Comment by pamasse** [comment]
There are an issue with the version of the chrome driver to test the application. This PR is correct and can be merged.

**Review by matsduf — APPROVED** [review]

**Comment by pamasse** [comment]
@matsduf who do the merge?

**Pull request merged**
