### PR TITLE
Improve code quality

### PR DESCRIPTION
**Pull request by pamasse**
In order to improve code quality of this repo i installed some linter and configured git hooks.
The hooks will be run before each commit to be sure that the code is align with the linters rules.

### CODE REVIEW

**Comment by sandoche2k** [comment]
@matsduf & @pnax can you check the changes?

**Comment by pamasse** [comment]
I also need to rebase the code to avoid conflicts

**Review by matsduf — APPROVED** [review]
This is a very large PR, and it is impossible to review it without a complete test of it. What I have seen, most changes are just formatting changes. I trust it and I will approve it again when the conflict has been resolved. I assume that @pamasse will be able to resolve issues that might appear during testing.

**Comment by sandoche2k** [comment]
Agreed. It should be merged.

**Comment by pamasse** [comment]
I'm totally available to resolve any issues. By the way, I'm still
connected to the zonemaster slack channel if necessary.

Le mer. 23 sept. 2020 à 13:31, Mats Dufberg <notifications@github.com> a écrit :
>
> @matsduf approved this pull request.
>
> This is a very large PR, and it is impossible to review it without a complete test of it. What I have seen, most changes are just formatting changes. I trust it and I will approve it again when the conflict has been resolved. I assume that @pamasse will be able to resolve issues that might appear during testing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Pierre-Aymeric MASSE

**Comment by sandoche2k** [comment]
@pamasse I suggest you merge. And if there is any issue during test we will create new issues.

**Comment by matsduf** [comment]
Yes, please rebase and I'll approve again and you can merge.

**Review by pnax — COMMENTED** [review]
Aside the typos, this is fine for me.

Just a question though, is the code automatically formatted with the git hooks ?

**Comment by matsduf** [comment]
It looks like rebasing is needed.

**Review by matsduf — APPROVED** [review]

**Comment by pamasse** [comment]
Cleaner version => #144

**Pull request closed without merging**
