### PR TITLE
Deduplicate the assets directory

### PR DESCRIPTION
**Pull request by blacksponge**
## Purpose

Since the migration to @angular/localize one bundle is generated per locale. This duplicates the assets.

While for the images it is sub-optimal but acceptable, for the configuration it is not. A user should not be required to update 6 times (or more in the future) the configuration, it is unpractical and error prone.

This PR changes the way the release zip is built to only use one assets folder. The asset folder is colocated with the locales folder to form the following architecture.

```
└── dist
    ├── assets
    │   ├── css
    │   ├── faqs
    │   ├── favicon
    │   └── images
    ├── da
    ├── en
    ├── es
    ├── fi
    ├── fr
    ├── nb
    └── sv
```

This way the assets folder is only present once. Also it means that our previous documentation still applies as the configuration path as not changed. Users will not have to move/copy the configuration file else where and will be able to reuse the existing one.

## Context

#374 

## Changes

* Use only one asset directory for all locales.
* Correct a typo in documentation

## How to test this PR

* Deploy the GUI using the release zip and apache configuration.
* Images (ZM logo) should be displayed and configuration should be accessible (try setting a message banner for instance).
* FAQ should be accessible.

### CODE REVIEW

**Review by tgreenx — APPROVED** [review]
Works as expected, and also when using a [custom base url](https://github.com/zonemaster/zonemaster-gui/blob/develop/docs/Installation.md#serving-the-gui-and-api-from-a-custom-base-url).
Tested as part of 2022-2 release testing on Debian 11.

**Comment by matsduf** [comment]
@blacksponge, I am not against it, but what risks do you see doing this very late in the release cycle?

**Comment by blacksponge** [comment]
> I am not against it, but what risks do you see doing this very late in the release cycle?

I did the smallest changes that I could to reduce the risk, and it has already been tested on two OSs. I do not forsee much risks coming from that but I still prefer to take it than deferring to next release and have something half finished for this one.

**Review by pnax — APPROVED** [review]
I think this is fine to include it within this release.

**Comment by matsduf** [comment]
@blacksponge, is issue #374 fully resolved by this PR?

**Comment by blacksponge** [comment]
> is issue https://github.com/zonemaster/zonemaster-gui/issues/374 fully resolved by this PR?

Yes it is

**Pull request merged**
