### PR TITLE
fix(#138): Change sv to da value in the lang form

### PR DESCRIPTION
**Pull request by pamasse**
Change "SV" to "DA" in the select lang form for small screen (smartphone)
Fix issue #138

### CODE REVIEW

**Review by sandoche2k — APPROVED** [review]

**Review by matsduf — APPROVED** [review]
Fine!

**Comment by sandoche2k** [comment]
@pamasse if you have time, can you check why travis fails and merge?

**Review by pnax — APPROVED** [review]
Looks good to me. However I don't understand why travis fails...

**Comment by sandoche2k** [comment]
@pamasse reminder..

**Review by matsduf — CHANGES_REQUESTED** [review]
There are unrelated changes and commits in this PR as far as I can see. Can that be resolved?

**Comment by pamasse** [comment]
> There are unrelated changes and commits in this PR as far as I can see. Can that be resolved?

I forced github to check again the diff between branches. It's now fixed.

**Review by matsduf — APPROVED** [review]

**Pull request merged**
