### PR TITLE
Fix fragment in notice box

### LINKED ISSUE #147: Wrong link in notice box
When opening the «Options» box, a notice appears with the following link :

`What is an undelegated domain test? -> https://zonemaster.fr/faq#undelegated`

However the FAQ page is using a numeric anchor system. I think the link should be https://zonemaster.fr/faq#q12.

### PR DESCRIPTION
**Pull request by pnax**
This updates the fragment value in the notice box to link to the proper FAQ section.

This should fix #147

### CODE REVIEW

**Comment by pnax** [comment]
This requires fixing consistency between anchors for the 12th section in the FAQ for all language first. See https://github.com/zonemaster/zonemaster-gui/issues/147#issuecomment-718897106

**Review by mattias-p — DISMISSED** [review]

**Comment by pnax** [comment]
I just updated the values in the FAQ document based on the request in https://github.com/zonemaster/zonemaster-gui/issues/147#issuecomment-718911564

**Review by matsduf — CHANGES_REQUESTED** [review]
For this to be consistent with other fragments you should change
```
<a name="undelegated"></a>
```
to
```
<a name="q12"></a>
```
where it is not already.

```
$ grep "#undelegated" *
gui-faq-da.md:12. [Hvad er en "ikke-delegeret" test?](#undelegated)
gui-faq-fr.md:12. [C'est quoi un test sur un domaine non délégué?](#undelegated)

$ grep 'name="undelegated"' *
gui-faq-da.md:#### 12. Hvad er en "ikke-delegeret" test? <a name="undelegated"></a>
gui-faq-fr.md:#### 12. C'est quoi un test sur un nom de domaine non délégué ? <a name="undelegated"></a>
```

**Comment by pnax** [comment]
Good point, this should be fixed

**Comment by pnax** [comment]
Delete last update and revert to first commit in this PR.

* use `q12` to be consistent with other sections.
* update the unit test accordingly

**Review by matsduf — APPROVED** [review]

**Pull request merged**
