### PR TITLE
Added to make Travis test. Not to be kept.

### PR DESCRIPTION
**Pull request by matsduf**
## Purpose

Trigger Travis to test. Not to be merged.

## Context

#214 and #216 unexpectedly fails.

### CODE REVIEW

**Comment by blacksponge** [comment]
`.click` return a promise that resolve when the click has been done, could the error come from a race condition because we are not waiting for the promise to resolve in `Utils.setLang`?

**Comment by matsduf** [comment]
> `.click` return a promise that resolve when the click has been done, could the error come from a race condition because we are not waiting for the promise to resolve in `Utils.setLang`?

Could a sleep() be added to the test?

**Comment by blacksponge** [comment]
It could but if that is really the issue it would be better if we `await` the promise, something like that maybe
```diff
diff --git a/e2e/FR16.e2e-spec.ts b/e2e/FR16.e2e-spec.ts
index 0847764..26a62fb 100644
--- a/e2e/FR16.e2e-spec.ts
+++ b/e2e/FR16.e2e-spec.ts
@@ -16,12 +16,12 @@ describe('Zonemaster test FR16 - [The advanced view should have a text describin
     expect(element(by.css('.alert.alert-info')).element(by.css('a')).getAttribute('fragment')).toBe('q12');
   });
 
-  it('should have a description text in multi languages', () => {
-    utils.setLang('en');
+  it('should have a description text in multi languages', async () => {
+    await utils.setLang('en');
     expect(element(by.css('.alert.alert-info')).element(by.css('a')).getText()).toContain('undelegated');
-    utils.setLang('fr');
+    await utils.setLang('fr');
     expect(element(by.css('.alert.alert-info')).element(by.css('a')).getText()).toContain('non délégué');
-    utils.setLang('sv');
+    await utils.setLang('sv');
     expect(element(by.css('.alert.alert-info')).element(by.css('a')).getText()).toContain('odelegerat domäntest');
   });
 });
diff --git a/e2e/utils/app.utils.ts b/e2e/utils/app.utils.ts
index 7317541..a812802 100644
--- a/e2e/utils/app.utils.ts
+++ b/e2e/utils/app.utils.ts
@@ -10,7 +10,7 @@ export class Utils {
   }
 
   setLang(lang) {
-    element(by.xpath('//a[@lang="' + lang + '"]')).click();
+    return element(by.xpath('//a[@lang="' + lang + '"]')).click();
   }
 
   activeOptions() {
```

**Comment by matsduf** [comment]
@blacksponge, I agree that it sounds like a better idea. Have you created a PR on that?

**Comment by blacksponge** [comment]
Not yet, will do.

**Comment by blacksponge** [comment]
I opened #225, if that doesn't work we can try the sleep. I am actually unsure if it is the click event that has not finished or the loading of the translation

**Pull request closed without merging**
