### PR TITLE
Fix history call

### PR DESCRIPTION
**Pull request by pamasse**
Update the call to the history method in the new api

### CODE REVIEW

**Comment by sandoche2k** [comment]
How do you want me to include the modified data ?

**Comment by sandoche2k** [comment]
I tested with the following link : wget https://github.com/zonemaster/zonemaster-gui/releases/download/v2.1.0/zonemaster_web_gui.zip. 

History is not working. Test link : http://149.202.56.242/domain_check

**Comment by pamasse** [comment]
Ok, could you try to grep the main.js file in the dist folder of the zip file.
Please, unzip the zip file in a folder and grep the term "version"
`grep -o 'version.\{0,30\}' main.2db08509838a494ccf5d.bundle.js`

You must to catch something like this (for me it's the second line): 
> version:"2.1.0",id:"Zonemaster GUI"},

Then do the same for the /var/www/zonemaster/dist folder please. It's the same result ?
If yes, so you must see in the Web GUI that the version of the GUI is 2.1.0. 
Right now, when i visit  http://149.202.56.242/domain_check, i see v2.0.0 

Thanks

**Comment by sandoche2k** [comment]
```
grep -o 'version.\{0,30\}' main.dba26b103dfc41de9765.bundle.js
version",w.full),new Wr(a,new Br(a),s
version:"2.0.0",id:"Zonemaster GUI"},
version=this.clientInfo.version,t.cli
versionInfo=function(){return this.RP
version_info",{},!1)},e.prototype.pro
versionInfo().then(function(n){t.vers
version]),t},e}(),Ph=r._6({encapsulat
versions)},null)}function Ah(e){retur
versions. Non RFC2822/ISO date format
version="2.22.2",t=St,i.fn=dn,i.min=f
```

**Comment by sandoche2k** [comment]
when i try to download the link from the install doc in the develop branch, i get the following: 

```
 wget https://github.com/zonemaster/zonemaster-gui/releases/download/v3.0.0/zonemaster_web_gui.zip -O temp.zip
--2019-01-27 18:33:28--  https://github.com/zonemaster/zonemaster-gui/releases/download/v3.0.0/zonemaster_web_gui.zip
Resolving github.com (github.com)... 140.82.118.3, 140.82.118.4
Connecting to github.com (github.com)|140.82.118.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-27 18:33:29 ERROR 404: Not Found.
```
So, please update

**Comment by sandoche2k** [comment]
History is working; when i download via this link : 

wget https://github.com/zonemaster/zonemaster-gui/releases/download/v2.1.0/zonemaster_web_gui.zip -O temp.zip

So. You got to update the link in the install instructions

**Comment by pamasse** [comment]
Mats change the version for 3.0.0 in #20

**Pull request merged**
