### PR TITLE
Update fi.json

### LINKED ISSUE #288: Translation to Finnish (GUI)
For some messages in the GUI itself translation to Finnish is incomplete. The following items in [src/assets/i18n/fi.json] needs translation. Translation can either be provided as a pull request or as a comment to this issue. This issue replaces (incorporates) issue #245.

In [src/assets/i18n/fi.json]:
```json
    "Algorithm required": null,
    "All": null,
    "DELEGATED_PLURAL": null,
    "Digest type required": null,
    "Disable IPv4": null,
    "Disable IPv6": null,
    "NS required": null,
    "TOOLTIP_ALL": null,
    "TOOLTIP_CRITICAL": null,
    "TOOLTIP_ERROR": null,
    "TOOLTIP_INFO": null,
    "TOOLTIP_NOTICE": null,
    "TOOLTIP_WARNING": null,
    "UNDELEGATED_PLURAL": null,
    "UNDELEGATED_SINGULAR": null,
```

When the key is a TAG then the translation should be a translation of the value in [src/assets/i18n/en.json]:
```json
    "DELEGATED_PLURAL": "Delegated",
    "TOOLTIP_ALL": "Display all results",
    "TOOLTIP_CRITICAL": "Critical - means a very serious error.",
    "TOOLTIP_ERROR": "Error - means a problem that is very likely (or possibly certain) to negatively affect the function of the zone being tested, but not so severe that the entire zone becomes unresolvable",
    "TOOLTIP_INFO": "Info - is something that may be of interest to the zone's administrator but that definitely does not indicate a problem.",
    "TOOLTIP_NOTICE": "Notice - means something that should be known by the zone's administrator but that need not necessarily be a problem at all",
    "TOOLTIP_WARNING": "Warning - means something that will under some circumstances be a problem, but that is unlikely to be noticed by a casual user.",
    "UNDELEGATED_PLURAL": "Undelegated",
    "UNDELEGATED_SINGULAR": "Undelegated",
```

[src/assets/i18n/fi.json]: https://github.com/zonemaster/zonemaster-gui/blob/develop/src/assets/i18n/fi.json
[src/assets/i18n/en.json]: https://github.com/zonemaster/zonemaster-gui/blob/develop/src/assets/i18n/en.json

### PR DESCRIPTION
**Pull request by samisalmensuo**
Hopefully this works :)

## Purpose

This PR...

## Context

Resolves #288

## Changes

...

## How to test this PR

When Finnish has been selected, all buttons etc should show text in Finnish.

### CODE REVIEW

**Review by pnax — APPROVED** [review]
I tested it and it works :)

**Review by matsduf — APPROVED** [review]

**Review by matsduf — APPROVED** [review]
I approve. It looks fine.

**Comment by matsduf** [comment]
> I tested it and it works :)

Thanks. I just inspected.

**Comment by matsduf** [comment]
@samisalmensuo, thank you. All looks fine. Now it is merged, and you can remove the branch on your fork.

**Pull request merged**
