### PR TITLE
pin webdriver version

### LINKED ISSUE #210: Travis fails
Since recently Travis is failing. It might be because of the Chromedriver that uses a new version of Chrome.
See PR #207 where this has been discovered, especially these comments https://github.com/zonemaster/zonemaster-gui/pull/207#issuecomment-853144960 and https://github.com/zonemaster/zonemaster-gui/pull/207#issuecomment-853152984

Maybe the error is somewhere else... I have not much clue for now, but it would be nice to see Travis happy again ;)

### PR DESCRIPTION
**Pull request by blacksponge**
Fix #210

### CODE REVIEW

**Comment by mattias-p** [comment]
Does this mean that Chrome could introduce changes that are incompatible with Zonemaster GUI without us noticing?

**Comment by blacksponge** [comment]
Unfortunately, yes, before the issue with protractor/chrome-driver is fixed we can't update to the latest stable without the tests breaking. So I would suggest to pin the version temporally so that we can at least catch regression in our code base.

**Comment by mattias-p** [comment]
Maybe we could have an issue marked with milestone v2021.2 reminding us to revert the pinning?

**Comment by blacksponge** [comment]
Yes, we can track this directly in #210, or create an other one.

Another workaround would be to use the `browser.executeScript` API to fetch the attributes like this

```js
getAttribute(element, attribute) {
    return browser.executeScript(`return arguments[0][arguments[1]];`, element, attribute);
}
```

I'm not sure what the best thing to do would be, either way it should only be temporary.

**Comment by matsduf** [comment]
@pamasse, can you take a look at this?

**Review by pamasse — APPROVED** [review]

**Review by matsduf — APPROVED** [review]

**Comment by matsduf** [comment]
@blacksponge, please merge.

**Pull request merged**
