### PR TITLE
don't collapse expended modules when language changes

### PR DESCRIPTION
**Pull request by blacksponge**
## Purpose

When someone changes the language once the results are displayed, if one of the module is expended then is will be collapsed.

## Changes

This PR changes the behaviour of the result component to not re-collapse modules if the language has changed. 

When the result id changes the behaviour remains the same as before.

## How to test this PR

* Open a test results (ex. http://localhost:4200/result/df0aa98ff4e53b99 if your dev environment point to zonemaster.net)
* Expend a module
* Change the language
* If the module remains expended, it is working as expected
* Now try to change the result id by displaying another test from the history
* If all modules are now collapsed, it is working as expected

### CODE REVIEW

**Review by matsduf — APPROVED** [review]
This looks fine. It works as it should when tested. It improves the appearance when changing language.

Also here I would like to see more documentation of the code. In Perl there is POD for documentation. Is there something similar for this code.

**Review by pnax — APPROVED** [review]
Nice feature.

**Comment by matsduf** [comment]
@blacksponge, please merge.

**Comment by pnax** [comment]
## Testing v2021.2

- [x] If the module remains expended, it is working as expected
- [x] If all modules are now collapsed, it is working as expected

LGTM

**Pull request merged**
