### PR TITLE
update page title based on route

### PR DESCRIPTION
**Pull request by blacksponge**
## Purpose

Update the page title base on component displayed.

## Context

\-

## Changes

* Change title when browsing the FAQ.
* Display tested domain when a test in ongoing or when displaying the results.

## How to test this PR

* Create a new test, check that the domain is display in the title.
* When testing another domain from the result page, the title should change as soon as the other test starts.
* Go back in your browser history to see the first test.
* The title should contain the first domain.
* Go back again.
* The title should be back to "Zonemaster".
* Go to the FAQ.
* The title should contain "FAQ".

### CODE REVIEW

**Review by pnax — APPROVED** [review]
Nice feature! It's working well.

**Review by matsduf — APPROVED** [review]
I have not been able to test, but looks good to me.

**Comment by matsduf** [comment]
@blacksponge, please merge.

**Comment by matsduf** [comment]
@blacksponge, please merge.

**Comment by pnax** [comment]
I was doing some tests, and it seems that some translations don't use the FAQ word. Could the title be updated to use the translated term?

**Comment by blacksponge** [comment]
> Could the title be updated to use the translated term?

Good point, I addressed that in #313

**Pull request merged**
