### PR TITLE
Update dependencies

### LINKED ISSUE #108: "npm install" gives warnings and has vulnerabilities
16 high vulnerabilities and several warnings.

```
$ npm install
npm WARN @angular-devkit/build-angular@0.901.0 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.901.0 requires a peer of typescript@>=3.6 < 3.9 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.0 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.0 requires a peer of typescript@>=3.6 < 3.9 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-moment@3.0.1 requires a peer of @angular/common@>=2.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-moment@3.0.1 requires a peer of @angular/core@>=2.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN zonemaster-gui@3.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.0 (node_modules/karma/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/@angular/compiler-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 19994 packages in 21.048s

36 packages are looking for funding
  run `npm fund` for details

found 118 vulnerabilities (65 low, 37 moderate, 16 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

### PR DESCRIPTION
**Pull request by pamasse**
It's an update of dependencies.
The big change concerns our main framework, from Angular 8 to Angular 9.

To apply the changes, please delete the `node_modules` folder and run `npm install`

Fix #108 and #109

### CODE REVIEW

**Comment by pamasse** [comment]
The big change concerns the "core system" of angular, not our app. I personally test the main function with success (make test, display results, export csv or json, go to faqs etc...). 
So, yes, other change and "old" instructions are valid

**Comment by sandoche2k** [comment]
I did not succeed in creating the package for GUI with the update. Can you send me the zip package link to enable others to test the other components.

**Comment by matsduf** [comment]
I have tested, and I get no errors. I get a few warnings. @pamasse, the following warning looks like it could come from an error in our source code. It is emitted just before `npm run release` successfully ends.

```
WARNING in /home/matsd/git/zonemaster-gui/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

@pamasse, does something have to be corrected for the warning above?

Two sets of warnings from `npm install` but they do not look problematic.

```
> canvas@2.6.1 install /home/matsd/git/zonemaster-gui/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[canvas] Success: "/home/matsd/git/zonemaster-gui/node_modules/canvas/build/Release/canvas.node" is installed via remote
```

```
> @angular/cli@9.1.0 postinstall /home/matsd/git/zonemaster-gui/node_modules/@angular/cli
> node ./bin/postinstall/script.js

npm WARN zonemaster-gui@3.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by pamasse** [comment]
> 
> 
> I have tested, and I get no errors. I get a few warnings. @pamasse, the following warning looks like it could come from an error in our source code. It is emitted just before `npm run release` successfully ends.
> 
> ```
> WARNING in /home/matsd/git/zonemaster-gui/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
> Add only entry points to the 'files' or 'include' properties in your tsconfig.
> ```
> 
> @pamasse, does something have to be corrected for the warning above?
> 
> Two sets of warnings from `npm install` but they do not look problematic.
> 
> ```
> > canvas@2.6.1 install /home/matsd/git/zonemaster-gui/node_modules/canvas
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> [canvas] Success: "/home/matsd/git/zonemaster-gui/node_modules/canvas/build/Release/canvas.node" is installed via remote
> ```
> 
> ```
> > @angular/cli@9.1.0 postinstall /home/matsd/git/zonemaster-gui/node_modules/@angular/cli
> > node ./bin/postinstall/script.js
> 
> npm WARN zonemaster-gui@3.1.0 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> ```

The environnement.prod.ts warning will be fix later. For the moment, i don't know how to remove this warning since i use the file during the generation of the release file.

Warning from npm install are about fsevents which is a macos dependency. Since you are not on MacOS (darwin), NPM tell you that the package will not be installed.

**Pull request merged**
