### PR TITLE
Update copyright year to 2021

### PR DESCRIPTION
**Pull request by pnax**
## Purpose

The copyright statement is still 2020. This updates it to 2021.

## Context

Addresses #188 (well not exactly because the issue is about to dynamically setting the year).

## Changes

Update the footer component inner HTML.

## How to test this PR

Look that the copyright statement displays the current year.

## Final note

I am no jurist, but do we really need this copyright statement ?

### CODE REVIEW

**Comment by matsduf** [comment]
I do not think means much if the year is correct or not.

**Comment by pnax** [comment]
> Could we defer this to v2021.2?

From my point of view this is totally fine.

> I do not think means much if the year is correct or not.

I don't know either. I would even suggest to remove the whole copyright statement if we think it is not needed. We can keep something like `developed and maintained by Afnic and The Swedish Internet Foundation since 2013` (but this would be another PR if you all agree on that).

I'll leave this PR open for now. Feel free to comment on the need of the copyright statement (and if yes, what should go in it).

**Comment by matsduf** [comment]
My proposal:
* Update this PR to remove year from this place. It is enough with the copyright statement.
* We have year in the [LICENSE] file. 
  * Ask lawyers if needed.
  * If it should be there we have to include in the release process to update it in all repositories, else remove it from all such files.

[LICENSE]: https://github.com/zonemaster/zonemaster-gui/blob/master/LICENSE

**Review by mattias-p — APPROVED** [review]

**Comment by mattias-p** [comment]
What is it we're claiming copyright for anyway? This copyright statement is in HTML. Does the copyright statement cover the user interface? Maybe the text in the FAQ? It shows up on pages that show test results, but I doubt we want those to be covered by copyright.

**Review by matsduf — CHANGES_REQUESTED** [review]
Deprecated by #215

**Comment by pnax** [comment]
Not relevant anymore, since #215 removes the year.

**Pull request closed without merging**
