### PR TITLE
improve form style on narrow devices

### PR DESCRIPTION
**Pull request by hannaeko**
## Purpose

Make usability on mobile devices slightly better.

## Context

Addresses #255 

## Changes

* Make the progress bar on xs devices the same on as larger ones
* Correctly align the input and submit button
* Fix line break on NS form group

## How to test this PR

* Open the GUI on a small device / using the browser mobile view tool
* Start a test

### CODE REVIEW

**Comment by blacksponge** [comment]
@matsduf can you review this?

**Review by matsduf — DISMISSED** [review]

**Review by pnax — DISMISSED** [review]

**Comment by matsduf** [comment]
@blacksponge, please merge.

**Review by matsduf — APPROVED** [review]
This is fine. I approve again.

**Comment by pnax** [comment]
## Testing v2021.2

lgtm

**Pull request merged**
